import { Router } from 'express';
import * as c0 from '@controllers/admin/add-casual-leave/controller';
import * as c1 from '@controllers/admin/add-client/controller';
import * as c2 from '@controllers/admin/add-holiday/controller';
import * as c3 from '@controllers/admin/add-leave/controller';
import * as c4 from '@controllers/admin/add-manual-time/controller';
import * as c5 from '@controllers/admin/add-project/controller';
import * as c6 from '@controllers/admin/add-salary/controller';
import * as c7 from '@controllers/admin/add-user/controller';
import * as c8 from '@controllers/admin/alternate-tracker-flag/controller';
import * as c9 from '@controllers/admin/check-slip-otp/controller';
import * as c10 from '@controllers/admin/delete-holiday/controller';
import * as c11 from '@controllers/admin/delete-leave/controller';
import * as c12 from '@controllers/admin/delete-old-screenshots/controller';
import * as c13 from '@controllers/admin/delete-project/controller';
import * as c14 from '@controllers/admin/delete-salary/controller';
import * as c15 from '@controllers/admin/delete-user/controller';
import * as c16 from '@controllers/admin/electron-get-users/controller';
import * as c17 from '@controllers/admin/get-clients/controller';
import * as c18 from '@controllers/admin/get-holidays/controller';
import * as c19 from '@controllers/admin/get-project/controller';
import * as c20 from '@controllers/admin/get-project-detail/controller';
import * as c21 from '@controllers/admin/get-project-list-company/controller';
import * as c22 from '@controllers/admin/get-project-report/controller';
import * as c23 from '@controllers/admin/get-projects/controller';
import * as c24 from '@controllers/admin/get-salaries/controller';
import * as c25 from '@controllers/admin/get-user/controller';
import * as c26 from '@controllers/admin/get-user-detail/controller';
import * as c27 from '@controllers/admin/get-user-leaves/controller';
import * as c28 from '@controllers/admin/get-users/controller';
import * as c29 from '@controllers/admin/get-users-by-projectId/controller';
import * as c30 from '@controllers/admin/new-year-leaves/controller';
import * as c31 from '@controllers/admin/otp-for-download-slip/controller';
import * as c32 from '@controllers/admin/send-daily-mail/controller';
import * as c33 from '@controllers/admin/update-leave/controller';
import * as c34 from '@controllers/admin/update-user-status/controller';
import * as c35 from '@controllers/admin/user-screen-shots/controller';

const router = Router();

router.post('/add-casual-leave', c0.post);
router.post('/add-client', c1.post);
router.post('/add-holiday', c2.post);
router.post('/add-leave', c3.post);
router.get('/add-leave', c3.get);
router.post('/add-manual-time', c4.post);
router.post('/add-project', c5.post);
router.post('/add-salary', c6.post);
router.post('/add-user', c7.post);
router.post('/alternate-tracker-flag', c8.post);
router.post('/check-slip-otp', c9.post);
router.delete('/delete-holiday', c10.del);
router.delete('/delete-leave', c11.del);
router.post('/delete-old-screenshots', c12.post);
router.delete('/delete-project', c13.del);
router.delete('/delete-salary', c14.del);
router.delete('/delete-user', c15.del);
router.post('/electron-get-users', c16.post);
router.post('/get-clients', c17.post);
router.post('/get-holidays', c18.post);
router.post('/get-project', c19.post);
router.post('/get-project-detail', c20.post);
router.post('/get-project-list-company', c21.post);
router.post('/get-project-report', c22.post);
router.post('/get-projects', c23.post);
router.post('/get-salaries', c24.post);
router.post('/get-user', c25.post);
router.post('/get-user-detail', c26.post);
router.post('/get-user-leaves', c27.post);
router.post('/get-users', c28.post);
router.post('/get-users-by-projectId', c29.post);
router.post('/new-year-leaves', c30.post);
router.post('/otp-for-download-slip', c31.post);
router.post('/send-daily-mail', c32.post);
router.post('/update-leave', c33.post);
router.post('/update-user-status', c34.post);
router.post('/user-screen-shots', c35.post);

export default router;
