import { Router } from 'express';
import * as c0 from '@controllers/task/close-inactive-sessions/controller';
import * as c1 from '@controllers/task/compare-screenshot/controller';
import * as c2 from '@controllers/task/create-task/controller';
import * as c3 from '@controllers/task/delete-task/controller';
import * as c4 from '@controllers/task/electron-compare-screenshot/controller';
import * as c5 from '@controllers/task/electron-create-task/controller';
import * as c6 from '@controllers/task/electron-get-project-userId/controller';
import * as c7 from '@controllers/task/electron-screen-shots/controller';
import * as c8 from '@controllers/task/electron-stop-timer/controller';
import * as c9 from '@controllers/task/electron-update-last-active-time/controller';
import * as c10 from '@controllers/task/get-daily-hours/controller';
import * as c11 from '@controllers/task/get-project-userId/controller';
import * as c12 from '@controllers/task/get-task-sessions/controller';
import * as c13 from '@controllers/task/get-today-hours/controller';
import * as c14 from '@controllers/task/screen-shot/controller';
import * as c15 from '@controllers/task/screen-shots/controller';
import * as c16 from '@controllers/task/stop-timer/controller';
import * as c17 from '@controllers/task/task-list/controller';
import * as c18 from '@controllers/task/update-last-active-time/controller';
import * as c19 from '@controllers/task/update-recording-time/controller';
import * as c20 from '@controllers/task/update-task-time/controller';
import { memoryUpload } from '@middleware/upload';

const router = Router();

router.post('/close-inactive-sessions', c0.post);
router.get('/close-inactive-sessions', c0.get);
router.post('/compare-screenshot', c1.post);
router.post('/create-task', c2.post);
router.post('/delete-task', c3.post);
router.post('/electron-compare-screenshot', c4.post);
router.post('/electron-create-task', c5.post);
router.post('/electron-get-project-userId', c6.post);
router.post('/electron-screen-shots', c7.post);
router.post('/electron-stop-timer', c8.post);
router.post('/electron-update-last-active-time', c9.post);
router.post('/get-daily-hours', c10.post);
router.post('/get-project-userId', c11.post);
router.get('/get-task-sessions', c12.get);
router.post('/get-today-hours', c13.post);
router.post('/screen-shot', memoryUpload.single('image'), c14.post);
router.post('/screen-shots', c15.post);
router.post('/stop-timer', c16.post);
router.post('/task-list', c17.post);
router.post('/update-last-active-time', c18.post);
router.post('/update-recording-time', c19.post);
router.post('/update-task-time', c20.post);

export default router;
